name: minova
description: "A minimalist focus timer app."

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  slang: ^4.8.1
  slang_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.7.0
  slang_build_runner: ^4.8.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - i18n/

flutter_launcher_icons:
  image_path: "assets/images/icon.png"

  windows:
    generate: true
    image_path: "assets/images/icon_windows.png"

  android:
    generate: true
    image_path: "assets/images/icon.png"
    adaptive_icon_background: "#232323"
    adaptive_icon_foreground: "assets/images/icon_foreground.png"
