name: minova
description: "A minimalist focus timer app."

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.5.4
  slang_build_runner: ^4.8.0
  riverpod_generator: ^2.6.3
  hive_generator: ^2.0.1
  yaml: ^3.1.3
  path: ^1.9.1

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - i18n/

flutter_launcher_icons:
  image_path: "assets/images/icon.png"

  windows:
    generate: true
    image_path: "assets/images/icon_windows.png"

  android:
    generate: true
    image_path: "assets/images/icon.png"
    adaptive_icon_background: "#232323"
    adaptive_icon_foreground: "assets/images/icon_foreground.png"
